sudo: required
services:
  - docker

before_install:
  - docker build -t odemeringo/docker-react -f Dockerfile.dev .

script:
  - docker run -t odemeringo/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react-udemy"
  env: "DockerReactUdemy-env"
  bucket_name: "elasticbeanstalk-eu-west-1-814098365754"
  bucket_path: "docker-react-udemy"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
